### ISSUE TITLE
Add option of executing pre- and post- shell commands

### ISSUE THREAD

**Issue by ivotron** [ivotron/baseliner#2]
In `bench.yml`, add something like:

``` yaml
- name: run pre
  shell: '{{ item }}'
  with_items: '{{ bench.pre_commands }}'
```
